### ISSUE TITLE
On using GPS-Quests

### ISSUE THREAD

**Issue by VOIDDERtm** [PikaMug/Quests#1885]
### What is your Quests version / build number (do _not_ say "latest")?

Quests-4.2.0.jar

### Describe the problem and how to replicate it.

On using plugins GPS-Quests his not work. The GPS plugin works separately with commands
GPSQuests-1.5.jar

### Any console errors to share?

```shell
[12:20:29 ERROR]: Could not pass event QuestUpdateCompassEvent to GPS-Quests v1.5
java.lang.NoSuchMethodError: 'me.blackvein.quests.Quest me.blackvein.quests.events.quest.QuestUpdateCompassEvent.getQuest()'
        at me.pikamug.gpsquests.GPSQuests$QuestsListener.onQuestUpdateCompass(GPSQuests.java:149) ~[GPSQuests-1.5.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1547]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at me.blackvein.quests.Quest.lambda$updateCompass$0(Quest.java:550) ~[Quests-4.2.0.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1578) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1501) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1547]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### If applicable, can you provide an example quest from quests.yml?

```shell
# For non-English characters, this file MUST stay encoded in UTF-8
quests:
  custom1:
    name: Начало приключения
    ask-message: '§aКараванщик§f: Вот черт! Эй ты там в порядке? Похоже, мы обо что-то
      ударились.'
    finish-message: '&7Ну вот и началось мое приключение, еще бы знать куда это меня
      отправили... Ну и нужно хоть оружие купить или сделать, а то умирать ох как
      не хочется...'
    stages:
      ordered:
        '1':
          npc-ids-to-talk-to:
          - 0
          start-message: '&7Нужно бы узнать что произошло...'
          complete-message: '&aКараванщик&f: Клянусь, я бьюсь об эту чертову глыбу
            каждый раз во время этих путешествий.'
          objective-override:
          - Поговорить с караванщиком
        '2':
          locations-to-reach:
          - world 502.0 66.0 1805.0
          reach-location-radii:
          - 5
          reach-location-names:
          - Деревня Руар
          start-message: '&aКараванщик&7: Ну почти доехали, отсюда идет прямая дорога.
            Иди на юг по дороге, там уже и будет деревня Руар.'
          complete-message: '&7Деревни я достиг, нужно узнать где здесь староста,
            хоть познакомиться нужно.'
          objective-override:
          - Добраться до деревни Руар
        '3':
          npc-ids-to-talk-to:
          - 1
          complete-message: '&aСтароста&7: О еще один прибыл. Так-с, *ковыряется в
            бумагах*. Ты значит %player% будешь. И вот чего же тебе дома то не сиделось...'
          objective-override:
          - Нужно найти и поговорить со старостой
        '4':
          npc-ids-to-talk-to:
          - 1
          start-message: '&aСтароста&7: Ну да не мое это дело, раз дошел, то добро
            пожаловать, это деревня Руар.'
          complete-message: '&aСтароста&7: Вот указанно, что это нужно выдать тебе,
            хотя вас за последнее время много сюда понаехало... Походи по деревне,
            да подбери себе что то, а то монстры в раз згрызут...'
          objective-override:
          - Что то староста не договорил, а где жалование по прибытии? Нужно с ним
            поговорить да и узнать.
    rewards:
      money: 100
      quest-points: 1
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```

**Comment by PikaMug** [comment]
Thanks, I will address this shortly. In the future, please use the support areas linked from the GPS-Quests page.
