### ISSUE TITLE
Spamming error Task #10 for Quests v3.6.5-b717 generated an exception java.lang.NoClassDefFoundError: org/bukkit/Particle

### ISSUE THREAD

**Issue by krytoss** [PikaMug/Quests#765]
**What is your Quests version / build number (do _not_ say "latest")?**
v3.6.5-b717

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Since I installed quests on my spigot 1.8.8, console is spamming this error:
https://pastebin.com/MWyC85Td
I have found a closed issue saying the issue was fixed, but it wasn't.

**Comment by PikaMug** [comment]
OP is referencing #756

Thanks, I'll look into it.

**Comment by PikaMug** [comment]
I just confirmed that particles are already working on 1.8 protocol, shown below:

![note](https://user-images.githubusercontent.com/2267126/55828459-7c856c80-5ada-11e9-9b46-e63bc675fe50.png)

The only way I was able to replicate your error was setting an invalid npc-effect in config.yml, so I've pushed a commit which will inform the console of the problem rather than spamming errors. Please try https://www.spigotmc.org/resources/quests.3711/ once it becomes available.
